channels:
  - pytorch      
  - conda-forge  
  - defaults     
dependencies:
  # Conda-managed dependencies
  - python=3.9   
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - cpuonly      
  - scikit-learn
  - ipykernel    
  - jupyter
  - pandas
  - "numpy<2.0"  
  - matplotlib
  - simpleitk    
  - requests     

  - pip
  - pip:
    - git+https://github.com/alleninstitute/abc_atlas_access.git 
